services:
  - type: web
    name: my-streaming-app-backend
    env: node
    buildCommand: 'npm install'
    startCommand: 'npm start'
    envVars:
      - key: PORT
        value: 5000
# This is a test comment to ensure file change is detected